// flow-typed signature: f618e422a1689acc2b0a3711ac4c89ad
// flow-typed version: <<STUB>>/@subspace/redimension_v^1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@subspace/redimension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@subspace/redimension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@subspace/redimension/build/rollup.config' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/redis_v2.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/flow-typed/npm/util-promisifyall_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redimension/lib/index' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/index' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension.perf' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension.spec' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redis.config' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@subspace/redimension/build/rollup.config.js' {
  declare module.exports: $Exports<'@subspace/redimension/build/rollup.config'>;
}
declare module '@subspace/redimension/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/jest_v23.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/redis_v2.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/redis_v2.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/rollup_vx.x.x'>;
}
declare module '@subspace/redimension/flow-typed/npm/util-promisifyall_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redimension/flow-typed/npm/util-promisifyall_vx.x.x'>;
}
declare module '@subspace/redimension/lib/index.js' {
  declare module.exports: $Exports<'@subspace/redimension/lib/index'>;
}
declare module '@subspace/redimension/src/index.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/index'>;
}
declare module '@subspace/redimension/src/redimension.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension'>;
}
declare module '@subspace/redimension/src/redimension.perf.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension.perf'>;
}
declare module '@subspace/redimension/src/redimension.spec.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension.spec'>;
}
declare module '@subspace/redimension/src/redis.config.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redis.config'>;
}
declare module '@subspace/redimension/src/types.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/types'>;
}
