// flow-typed signature: 111fce493c2bdd922d2c313981870400
// flow-typed version: <<STUB>>/@subspace/redux-module_v^0.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@subspace/redux-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@subspace/redux-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@subspace/redux-module/build/rollup.config' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/redux-observable_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/rxjs_v6.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/lib/index' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/src/index' {
  declare module.exports: any;
}

declare module '@subspace/redux-module/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@subspace/redux-module/build/rollup.config.js' {
  declare module.exports: $Exports<'@subspace/redux-module/build/rollup.config'>;
}
declare module '@subspace/redux-module/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/jest_v22.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/redux-observable_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/redux-observable_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/rollup_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/rxjs_v6.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/rxjs_v6.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@subspace/redux-module/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@subspace/redux-module/flow-typed/npm/webpack-cli_vx.x.x'>;
}
declare module '@subspace/redux-module/lib/index.js' {
  declare module.exports: $Exports<'@subspace/redux-module/lib/index'>;
}
declare module '@subspace/redux-module/src/index.js' {
  declare module.exports: $Exports<'@subspace/redux-module/src/index'>;
}
declare module '@subspace/redux-module/src/index.spec.js' {
  declare module.exports: $Exports<'@subspace/redux-module/src/index.spec'>;
}
