version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server-prod
    image: subspace/server
    container_name: subspace-server
    environment:
      NODE_ENV: production
      DB_NAME: ss
      DB_HOST: db-1
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client-prod
    image: subspace/client
    container_name: subspace-client
    ports:
      - 8082:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - net_frontend
