version: "3.3"
services:
  db-ui:
    image: cockroachdb/cockroach
    command: start --insecure
    expose:
      - 8080
      - 26257
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - db
  db-1:
    image: cockroachdb/cockroach
    command: start --insecure --join=db-ui
    networks:
      - db
    volumes:
      - ./data/db-1:/cockroach/cockroach-data
  redis:
    image: redis
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    image: subspace/server
    environment:
      PORT: 8081
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - backend
      - frontend
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client
    image: subspace/client
    ports:
      - 8082:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - frontend
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --no-auth
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_portainer:/data
    networks:
      - tools
volumes:
  data_portainer:
networks:
  frontend:
  backend:
  db:
  tools:
