// flow-typed signature: 474d4c67a4b9b0458f7f30dd304db124
// flow-typed version: <<STUB>>/source-map-loader_v^0.2.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'source-map-loader/index' {
  declare module.exports: $Exports<'source-map-loader'>;
}
declare module 'source-map-loader/index.js' {
  declare module.exports: $Exports<'source-map-loader'>;
}
