// flow-typed signature: 8875ac537b1773d6ad907e2aaed61adb
// flow-typed version: <<STUB>>/virtual-clock_v1.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'virtual-clock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'virtual-clock' {
  declare module.exports: any;
}
