// flow-typed signature: db2e74d509557bbde235f775cc34739e
// flow-typed version: <<STUB>>/web-udp_v^1.2.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-udp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "web-udp" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "web-udp/dist/client" {
  declare module.exports: any
}

declare module "web-udp/lib/server" {
  declare module.exports: any
}

// Filename aliases
declare module "web-udp/dist/client.js" {
  declare module.exports: $Exports<"web-udp/dist/client">
}
declare module "web-udp/lib/server.js" {
  declare module.exports: $Exports<"web-udp/lib/server">
}
