// flow-typed signature: f168a1e35c066e7c5b8cd40d274ad337
// flow-typed version: <<STUB>>/@subspace/core_v^0.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@subspace/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@subspace/core" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@subspace/core/actions/index" {
  declare module.exports: any
}

declare module "@subspace/core/middleware/loop" {
  declare module.exports: any
}

declare module "@subspace/core/model/game" {
  declare module.exports: any
}

declare module "@subspace/core/store/index" {
  declare module.exports: any
}

declare module "@subspace/core/types/scheduler" {
  declare module.exports: any
}

// Filename aliases
declare module "@subspace/core/actions/index.js" {
  declare module.exports: $Exports<"@subspace/core/actions/index">
}
declare module "@subspace/core/index" {
  declare module.exports: $Exports<"@subspace/core">
}
declare module "@subspace/core/index.js" {
  declare module.exports: $Exports<"@subspace/core">
}
declare module "@subspace/core/middleware/loop.js" {
  declare module.exports: $Exports<"@subspace/core/middleware/loop">
}
declare module "@subspace/core/model/game.js" {
  declare module.exports: $Exports<"@subspace/core/model/game">
}
declare module "@subspace/core/store/index.js" {
  declare module.exports: $Exports<"@subspace/core/store/index">
}
declare module "@subspace/core/types/scheduler.js" {
  declare module.exports: $Exports<"@subspace/core/types/scheduler">
}
