// flow-typed signature: c58c418b3a1927c81247c6b3541de773
// flow-typed version: <<STUB>>/@subspace/core_v^0.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@subspace/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@subspace/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@subspace/core/build/rollup.config' {
  declare module.exports: any;
}

declare module '@subspace/core/build/worker.rollup.config' {
  declare module.exports: any;
}

declare module '@subspace/core/lib/index' {
  declare module.exports: any;
}

declare module '@subspace/core/lib/p2-world.worker' {
  declare module.exports: any;
}

declare module '@subspace/core/src/extensions/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/extensions/subject/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/extensions/subject/web-udp-connection-subject' {
  declare module.exports: any;
}

declare module '@subspace/core/src/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/auth' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/entity' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/input' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/physics' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/ship-type' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/ship' {
  declare module.exports: any;
}

declare module '@subspace/core/src/model/user' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/p2/local' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/p2/util' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/p2/worker/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/p2/worker/p2-world.worker' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/snapshot-buffer' {
  declare module.exports: any;
}

declare module '@subspace/core/src/physics/types' {
  declare module.exports: any;
}

declare module '@subspace/core/src/protocol/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/epics/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/epics/loop' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/epics/physics' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/epics/user' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Async/Async' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Async/Async.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Async/constants' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Async/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Async/util' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Auth/Auth' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Auth/Auth.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Auth/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Loop/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Loop/Loop' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Loop/Loop.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Physics/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Physics/Physics' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Physics/Physics.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Ships/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Ships/Ships' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Ships/Ships.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Users/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Users/Users' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/modules/Users/Users.spec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/reducers' {
  declare module.exports: any;
}

declare module '@subspace/core/src/state/selectors/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/types/actions' {
  declare module.exports: any;
}

declare module '@subspace/core/src/types/index' {
  declare module.exports: any;
}

declare module '@subspace/core/src/util/vec' {
  declare module.exports: any;
}

declare module '@subspace/core/src/util/vec2' {
  declare module.exports: any;
}

// Filename aliases
declare module '@subspace/core/build/rollup.config.js' {
  declare module.exports: $Exports<'@subspace/core/build/rollup.config'>;
}
declare module '@subspace/core/build/worker.rollup.config.js' {
  declare module.exports: $Exports<'@subspace/core/build/worker.rollup.config'>;
}
declare module '@subspace/core/lib/index.js' {
  declare module.exports: $Exports<'@subspace/core/lib/index'>;
}
declare module '@subspace/core/lib/p2-world.worker.js' {
  declare module.exports: $Exports<'@subspace/core/lib/p2-world.worker'>;
}
declare module '@subspace/core/src/extensions/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/extensions/index'>;
}
declare module '@subspace/core/src/extensions/subject/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/extensions/subject/index'>;
}
declare module '@subspace/core/src/extensions/subject/web-udp-connection-subject.js' {
  declare module.exports: $Exports<'@subspace/core/src/extensions/subject/web-udp-connection-subject'>;
}
declare module '@subspace/core/src/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/index'>;
}
declare module '@subspace/core/src/model/auth.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/auth'>;
}
declare module '@subspace/core/src/model/entity.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/entity'>;
}
declare module '@subspace/core/src/model/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/index'>;
}
declare module '@subspace/core/src/model/input.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/input'>;
}
declare module '@subspace/core/src/model/physics.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/physics'>;
}
declare module '@subspace/core/src/model/ship-type.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/ship-type'>;
}
declare module '@subspace/core/src/model/ship.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/ship'>;
}
declare module '@subspace/core/src/model/user.js' {
  declare module.exports: $Exports<'@subspace/core/src/model/user'>;
}
declare module '@subspace/core/src/physics/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/index'>;
}
declare module '@subspace/core/src/physics/p2/local.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/p2/local'>;
}
declare module '@subspace/core/src/physics/p2/util.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/p2/util'>;
}
declare module '@subspace/core/src/physics/p2/worker/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/p2/worker/index'>;
}
declare module '@subspace/core/src/physics/p2/worker/p2-world.worker.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/p2/worker/p2-world.worker'>;
}
declare module '@subspace/core/src/physics/snapshot-buffer.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/snapshot-buffer'>;
}
declare module '@subspace/core/src/physics/types.js' {
  declare module.exports: $Exports<'@subspace/core/src/physics/types'>;
}
declare module '@subspace/core/src/protocol/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/protocol/index'>;
}
declare module '@subspace/core/src/state/epics/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/epics/index'>;
}
declare module '@subspace/core/src/state/epics/loop.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/epics/loop'>;
}
declare module '@subspace/core/src/state/epics/physics.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/epics/physics'>;
}
declare module '@subspace/core/src/state/epics/user.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/epics/user'>;
}
declare module '@subspace/core/src/state/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/index'>;
}
declare module '@subspace/core/src/state/modules/Async/Async.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Async/Async'>;
}
declare module '@subspace/core/src/state/modules/Async/Async.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Async/Async.spec'>;
}
declare module '@subspace/core/src/state/modules/Async/constants.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Async/constants'>;
}
declare module '@subspace/core/src/state/modules/Async/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Async/index'>;
}
declare module '@subspace/core/src/state/modules/Async/util.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Async/util'>;
}
declare module '@subspace/core/src/state/modules/Auth/Auth.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Auth/Auth'>;
}
declare module '@subspace/core/src/state/modules/Auth/Auth.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Auth/Auth.spec'>;
}
declare module '@subspace/core/src/state/modules/Auth/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Auth/index'>;
}
declare module '@subspace/core/src/state/modules/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/index'>;
}
declare module '@subspace/core/src/state/modules/Loop/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Loop/index'>;
}
declare module '@subspace/core/src/state/modules/Loop/Loop.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Loop/Loop'>;
}
declare module '@subspace/core/src/state/modules/Loop/Loop.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Loop/Loop.spec'>;
}
declare module '@subspace/core/src/state/modules/Physics/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Physics/index'>;
}
declare module '@subspace/core/src/state/modules/Physics/Physics.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Physics/Physics'>;
}
declare module '@subspace/core/src/state/modules/Physics/Physics.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Physics/Physics.spec'>;
}
declare module '@subspace/core/src/state/modules/Ships/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Ships/index'>;
}
declare module '@subspace/core/src/state/modules/Ships/Ships.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Ships/Ships'>;
}
declare module '@subspace/core/src/state/modules/Ships/Ships.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Ships/Ships.spec'>;
}
declare module '@subspace/core/src/state/modules/Users/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Users/index'>;
}
declare module '@subspace/core/src/state/modules/Users/Users.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Users/Users'>;
}
declare module '@subspace/core/src/state/modules/Users/Users.spec.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/modules/Users/Users.spec'>;
}
declare module '@subspace/core/src/state/reducers.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/reducers'>;
}
declare module '@subspace/core/src/state/selectors/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/state/selectors/index'>;
}
declare module '@subspace/core/src/types/actions.js' {
  declare module.exports: $Exports<'@subspace/core/src/types/actions'>;
}
declare module '@subspace/core/src/types/index.js' {
  declare module.exports: $Exports<'@subspace/core/src/types/index'>;
}
declare module '@subspace/core/src/util/vec.js' {
  declare module.exports: $Exports<'@subspace/core/src/util/vec'>;
}
declare module '@subspace/core/src/util/vec2.js' {
  declare module.exports: $Exports<'@subspace/core/src/util/vec2'>;
}
