// flow-typed signature: 515c38de6a79bf73901ad88762c0c603
// flow-typed version: <<STUB>>/@subspace/redimension_v^1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@subspace/redimension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@subspace/redimension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@subspace/redimension/build/rollup.config' {
  declare module.exports: any;
}

declare module '@subspace/redimension/lib/index' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/index' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension.perf' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redimension.spec' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/redis.config' {
  declare module.exports: any;
}

declare module '@subspace/redimension/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@subspace/redimension/build/rollup.config.js' {
  declare module.exports: $Exports<'@subspace/redimension/build/rollup.config'>;
}
declare module '@subspace/redimension/lib/index.js' {
  declare module.exports: $Exports<'@subspace/redimension/lib/index'>;
}
declare module '@subspace/redimension/src/index.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/index'>;
}
declare module '@subspace/redimension/src/redimension.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension'>;
}
declare module '@subspace/redimension/src/redimension.perf.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension.perf'>;
}
declare module '@subspace/redimension/src/redimension.spec.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redimension.spec'>;
}
declare module '@subspace/redimension/src/redis.config.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/redis.config'>;
}
declare module '@subspace/redimension/src/types.js' {
  declare module.exports: $Exports<'@subspace/redimension/src/types'>;
}
