// flow-typed signature: b9ba3a51e84c21b2dbe57c87b41e7dae
// flow-typed version: <<STUB>>/@web-udp/client_v^2.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@web-udp/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@web-udp/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@web-udp/client/build/webpack.config' {
  declare module.exports: any;
}

declare module '@web-udp/client/dist/index.browser' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/client' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/provider/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/provider/web-rtc/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/provider/web-rtc/rtc-channel' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/provider/web-rtc/rtc-connection-provider' {
  declare module.exports: any;
}

declare module '@web-udp/client/lib/provider/web-rtc/rtc-peer' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/client' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/client.spec' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/web-rtc/index' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/web-rtc/rtc-channel' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/web-rtc/rtc-connection-provider' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/web-rtc/rtc-connection-provider.spec' {
  declare module.exports: any;
}

declare module '@web-udp/client/src/provider/web-rtc/rtc-peer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@web-udp/client/build/webpack.config.js' {
  declare module.exports: $Exports<'@web-udp/client/build/webpack.config'>;
}
declare module '@web-udp/client/dist/index.browser.js' {
  declare module.exports: $Exports<'@web-udp/client/dist/index.browser'>;
}
declare module '@web-udp/client/lib/client.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/client'>;
}
declare module '@web-udp/client/lib/index.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/index'>;
}
declare module '@web-udp/client/lib/provider/index.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/provider/index'>;
}
declare module '@web-udp/client/lib/provider/web-rtc/index.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/provider/web-rtc/index'>;
}
declare module '@web-udp/client/lib/provider/web-rtc/rtc-channel.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/provider/web-rtc/rtc-channel'>;
}
declare module '@web-udp/client/lib/provider/web-rtc/rtc-connection-provider.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/provider/web-rtc/rtc-connection-provider'>;
}
declare module '@web-udp/client/lib/provider/web-rtc/rtc-peer.js' {
  declare module.exports: $Exports<'@web-udp/client/lib/provider/web-rtc/rtc-peer'>;
}
declare module '@web-udp/client/src/client.js' {
  declare module.exports: $Exports<'@web-udp/client/src/client'>;
}
declare module '@web-udp/client/src/client.spec.js' {
  declare module.exports: $Exports<'@web-udp/client/src/client.spec'>;
}
declare module '@web-udp/client/src/index.js' {
  declare module.exports: $Exports<'@web-udp/client/src/index'>;
}
declare module '@web-udp/client/src/provider/index.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/index'>;
}
declare module '@web-udp/client/src/provider/web-rtc/index.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/web-rtc/index'>;
}
declare module '@web-udp/client/src/provider/web-rtc/rtc-channel.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/web-rtc/rtc-channel'>;
}
declare module '@web-udp/client/src/provider/web-rtc/rtc-connection-provider.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/web-rtc/rtc-connection-provider'>;
}
declare module '@web-udp/client/src/provider/web-rtc/rtc-connection-provider.spec.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/web-rtc/rtc-connection-provider.spec'>;
}
declare module '@web-udp/client/src/provider/web-rtc/rtc-peer.js' {
  declare module.exports: $Exports<'@web-udp/client/src/provider/web-rtc/rtc-peer'>;
}
