// flow-typed signature: 7fd465a2bd9c2d0c4257c841a7bf2fc3
// flow-typed version: <<STUB>>/@babel/node_v^7.0.0-beta.41/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@babel/node" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@babel/node/bin/babel-node" {
  declare module.exports: any
}

declare module "@babel/node/lib/_babel-node" {
  declare module.exports: any
}

declare module "@babel/node/lib/babel-node" {
  declare module.exports: any
}

// Filename aliases
declare module "@babel/node/bin/babel-node.js" {
  declare module.exports: $Exports<"@babel/node/bin/babel-node">
}
declare module "@babel/node/lib/_babel-node.js" {
  declare module.exports: $Exports<"@babel/node/lib/_babel-node">
}
declare module "@babel/node/lib/babel-node.js" {
  declare module.exports: $Exports<"@babel/node/lib/babel-node">
}
