// flow-typed signature: 063fb52a577949a094e04830567a73b2
// flow-typed version: <<STUB>>/@babel/plugin-transform-runtime_v^7.0.0-beta.45/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@babel/plugin-transform-runtime" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@babel/plugin-transform-runtime/lib/definitions" {
  declare module.exports: any
}

declare module "@babel/plugin-transform-runtime/lib/index" {
  declare module.exports: any
}

// Filename aliases
declare module "@babel/plugin-transform-runtime/lib/definitions.js" {
  declare module.exports: $Exports<
    "@babel/plugin-transform-runtime/lib/definitions",
  >
}
declare module "@babel/plugin-transform-runtime/lib/index.js" {
  declare module.exports: $Exports<
    "@babel/plugin-transform-runtime/lib/index",
  >
}
