// flow-typed signature: 917c4f9b3a82bb2f5b5a3557c612bc8a
// flow-typed version: <<STUB>>/@babel/register_v7.0.0-beta.51/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/register' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/register/lib/browser' {
  declare module.exports: any;
}

declare module '@babel/register/lib/cache' {
  declare module.exports: any;
}

declare module '@babel/register/lib/index' {
  declare module.exports: any;
}

declare module '@babel/register/lib/node' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/register/lib/browser.js' {
  declare module.exports: $Exports<'@babel/register/lib/browser'>;
}
declare module '@babel/register/lib/cache.js' {
  declare module.exports: $Exports<'@babel/register/lib/cache'>;
}
declare module '@babel/register/lib/index.js' {
  declare module.exports: $Exports<'@babel/register/lib/index'>;
}
declare module '@babel/register/lib/node.js' {
  declare module.exports: $Exports<'@babel/register/lib/node'>;
}
