FROM node:9.8.0

WORKDIR /opt/subspace-server

EXPOSE 8080

# npm manifests
COPY package*.json ./

# monorepo configs/utils
RUN npm i lerna -g --loglevel notice
COPY lerna.json .

# dev configs/utils
COPY build ./build
COPY .eslintrc.json .
COPY .eslintignore .
COPY .babelrc .

# package and monorepo dependencies
COPY packages/core ./packages/core
COPY packages/server ./packages/server

# install dependencies and build
RUN npm i --loglevel notice
RUN lerna bootstrap

# rebuild wrtc on container architecture
RUN npm --prefix packages/server rebuild wrtc --update-binary

# set non-root user
USER node

# serve
CMD ["npm", "run", "--prefix", "packages/server", "serve"]
