FROM node:9.8.0

WORKDIR /opt/subspace

RUN npm i lerna -g --unsafe-perm --loglevel notice

RUN chown -R node:node /opt/subspace/

COPY package*.json lerna.json .eslintrc.json .eslintignore .babelrc ./

# package and monorepo dependencies
COPY packages/core/package*.json ./packages/core/
COPY packages/client/package*.json ./packages/client/

# install dependencies and build
RUN npm i --loglevel notice
RUN lerna bootstrap --ignore-scripts

RUN npm cache clean --force

USER node

# serve
CMD npm run dev:client
