FROM node:9.8.0

WORKDIR /opt/subspace

RUN npm config set unsafe-perm true
RUN npm i lerna -g --unsafe-perm --loglevel notice

RUN chown -R node:node /opt/subspace/

COPY package*.json lerna.json .eslintrc.json .eslintignore .babelrc ./

# package and monorepo dependencies
COPY packages/core/package*.json ./packages/core/
COPY packages/redux-module/package*.json ./packages/redux-module/
COPY packages/redimension/package*.json ./packages/redimension/
COPY packages/server/package*.json ./packages/server/

# install dependencies and build
RUN npm i --loglevel notice
RUN npm run bootstrap

# rebuild binaries on container architecture
RUN npm --prefix packages/server rebuild wrtc bcrypt --update-binary

RUN npm cache clean --force

# USER node

# serve
CMD bash -c "while ping -c1 db-init &>/dev/null; do :; done;" && \
    npm run dev:server
