// flow-typed signature: e38e763a124988ec0fbefb49e6a5a761
// flow-typed version: <<STUB>>/util-promisifyall_v^1.0.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'util-promisifyall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'util-promisifyall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'util-promisifyall/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'util-promisifyall/index' {
  declare module.exports: $Exports<'util-promisifyall'>;
}
declare module 'util-promisifyall/index.js' {
  declare module.exports: $Exports<'util-promisifyall'>;
}
declare module 'util-promisifyall/test/test.js' {
  declare module.exports: $Exports<'util-promisifyall/test/test'>;
}
