// flow-typed signature: 0c5dca0017b489fc1d65b8d74165eef0
// flow-typed version: <<STUB>>/@web-udp/server_v2.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@web-udp/server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@web-udp/server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@web-udp/server/build/webpack.config' {
  declare module.exports: any;
}

declare module '@web-udp/server/lib/index' {
  declare module.exports: any;
}

declare module '@web-udp/server/lib/server' {
  declare module.exports: any;
}

declare module '@web-udp/server/src/index' {
  declare module.exports: any;
}

declare module '@web-udp/server/src/server' {
  declare module.exports: any;
}

declare module '@web-udp/server/src/server.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@web-udp/server/build/webpack.config.js' {
  declare module.exports: $Exports<'@web-udp/server/build/webpack.config'>;
}
declare module '@web-udp/server/lib/index.js' {
  declare module.exports: $Exports<'@web-udp/server/lib/index'>;
}
declare module '@web-udp/server/lib/server.js' {
  declare module.exports: $Exports<'@web-udp/server/lib/server'>;
}
declare module '@web-udp/server/src/index.js' {
  declare module.exports: $Exports<'@web-udp/server/src/index'>;
}
declare module '@web-udp/server/src/server.js' {
  declare module.exports: $Exports<'@web-udp/server/src/server'>;
}
declare module '@web-udp/server/src/server.spec.js' {
  declare module.exports: $Exports<'@web-udp/server/src/server.spec'>;
}
